# Generated by Django 5.0.6 on 2024-06-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
